version: '2.8'

services:
  mssql:
    container_name: cash-register-sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: dvfgsp18_r36
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - cash-register-net
    volumes:
      - cash-register-data:/var/opt/mssql
    restart: unless-stopped
    hostname: cash-register-sql-server

networks:
  cash-register-net:
    driver: bridge
volumes:
  cash-register-data: