//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.711.0 using the following command:
// xscgen -n =CashRegister check01.xsd
namespace CashRegister.Api.Models.Dfs.Types
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.711.0")]
    [Serializable()]
    [System.Xml.Serialization.XmlTypeAttribute("DKPPColumn", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DKPPColumn
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// <para xml:lang="en">Pattern: ([\d]{2}\.[\d]{2}\.[\d]{2}-[\d]{2}(\.[\d]{1,2})*)|([\d]{2}\.[\d]{2}\.[\d]{2}(-[\d]{1,2})*)|([\d]{2}\.[\d]{2}(\.[\d]{1,2})*).</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([\\d]{2}\\.[\\d]{2}\\.[\\d]{2}-[\\d]{2}(\\.[\\d]{1,2})*)|([\\d]{2}\\.[\\d]{2}\\.[\\d]{2}(-[\\d" +
            "]{1,2})*)|([\\d]{2}\\.[\\d]{2}(\\.[\\d]{1,2})*)")]
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
    }
}
